from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
import io
from datetime import datetime
from typing import List, Dict

def generate_pdf_with_sources(topic: str, report_text: str, sources: List[Dict]) -> io.BytesIO:
    """
    Generate a professional PDF report with citations and bibliography.
    
    Args:
        topic: Investigation topic
        report_text: Full report text with citations
        sources: List of source dictionaries
    
    Returns:
        BytesIO buffer containing the PDF
    """
    
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75*inch, bottomMargin=0.75*inch)
    
    # Styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=24,
        textColor=colors.HexColor('#1a1a1a'),
        spaceAfter=30,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading1'],
        fontSize=16,
        textColor=colors.HexColor('#2c3e50'),
        spaceAfter=12,
        spaceBefore=20,
        fontName='Helvetica-Bold'
    )
    
    subheading_style = ParagraphStyle(
        'CustomSubHeading',
        parent=styles['Heading2'],
        fontSize=13,
        textColor=colors.HexColor('#34495e'),
        spaceAfter=10,
        spaceBefore=15,
        fontName='Helvetica-Bold'
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['BodyText'],
        fontSize=11,
        leading=16,
        alignment=TA_JUSTIFY,
        spaceAfter=12
    )
    
    citation_style = ParagraphStyle(
        'Citation',
        parent=styles['BodyText'],
        fontSize=9,
        leading=12,
        leftIndent=20,
        spaceAfter=10,
        textColor=colors.HexColor('#555555')
    )
    
    # Build document
    story = []
    
    # ============================================================================
    # COVER PAGE
    # ============================================================================
    
    story.append(Spacer(1, 1.5*inch))
    story.append(Paragraph("AI-AUGMENTED HYPOTHESIS EXPLORER", title_style))
    story.append(Paragraph("Evidence-Based Investigative Analysis", styles['Heading2']))
    story.append(Spacer(1, 0.5*inch))
    
    # Topic box
    story.append(Paragraph(f"<b>Investigation Topic:</b>", heading_style))
    story.append(Paragraph(topic, body_style))
    story.append(Spacer(1, 0.3*inch))
    
    # Metadata
    metadata = [
        ['Generated:', datetime.now().strftime('%B %d, %Y at %I:%M %p')],
        ['Total Sources:', str(len(sources))],
        ['Average Source Credibility:', f"{sum(s.get('credibility_score', 6.0) for s in sources) / len(sources):.2f}/10" if sources else "N/A"]
    ]
    
    metadata_table = Table(metadata, colWidths=[2*inch, 4*inch])
    metadata_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#ecf0f1')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#2c3e50')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
    ]))
    
    story.append(metadata_table)
    story.append(Spacer(1, 0.5*inch))
    
    # Disclaimer
    disclaimer = """
    <i>IMPORTANT DISCLAIMER: This report is generated by an AI system using web-sourced information. 
    While efforts are made to use credible sources, the analysis should be independently verified 
    before being used for critical decisions. Citations are provided for all factual claims.</i>
    """
    story.append(Paragraph(disclaimer, citation_style))
    
    story.append(PageBreak())
    
    # ============================================================================
    # MAIN REPORT
    # ============================================================================
    
    story.append(Paragraph("INVESTIGATIVE ANALYSIS REPORT", heading_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Process report text to handle citations
    report_paragraphs = report_text.split('\n\n')
    
    for para in report_paragraphs:
        if para.strip():
            # Detect headings (lines that are short and end without punctuation)
            if len(para) < 100 and not para.rstrip().endswith(('.', '!', '?', ':')):
                # Check if it looks like a heading
                if para.isupper() or para.startswith('**') or para.startswith('#'):
                    clean_para = para.replace('**', '').replace('#', '').strip()
                    story.append(Paragraph(clean_para, subheading_style))
                else:
                    story.append(Paragraph(para, body_style))
            else:
                story.append(Paragraph(para.replace('\n', '<br/>'), body_style))
    
    story.append(PageBreak())
    
    # ============================================================================
    # SOURCES & BIBLIOGRAPHY
    # ============================================================================
    
    story.append(Paragraph("EVIDENCE SOURCES & BIBLIOGRAPHY", heading_style))
    story.append(Spacer(1, 0.2*inch))
    
    if sources:
        story.append(Paragraph(
            f"This analysis is based on {len(sources)} verified web sources. "
            "Each source has been assigned a credibility score based on domain authority, "
            "publication reputation, and content quality.",
            body_style
        ))
        story.append(Spacer(1, 0.2*inch))
        
        # Create sources table
        source_data = [['#', 'Source', 'Credibility', 'Date']]
        
        for source in sources:
            source_num = source.get('id', '?')
            title = source.get('title', 'Unknown')[:60] + ('...' if len(source.get('title', '')) > 60 else '')
            credibility = f"{source.get('credibility_score', 6.0):.1f}/10"
            date = source.get('date', 'N/A')
            
            source_data.append([str(source_num), title, credibility, date])
        
        source_table = Table(source_data, colWidths=[0.5*inch, 4*inch, 1*inch, 1.2*inch])
        source_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#34495e')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
            ('TOPPADDING', (0, 0), (-1, 0), 10),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#ecf0f1')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')])
        ]))
        
        story.append(source_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Detailed source information
        story.append(Paragraph("DETAILED SOURCE INFORMATION", subheading_style))
        story.append(Spacer(1, 0.1*inch))
        
        for source in sources:
            source_num = source.get('id', '?')
            title = source.get('title', 'Unknown Title')
            url = source.get('url', 'No URL')
            snippet = source.get('snippet', 'No description available')
            credibility = source.get('credibility_score', 6.0)
            date = source.get('date', 'N/A')
            
            # Source header
            story.append(Paragraph(f"<b>[{source_num}] {title}</b>", body_style))
            
            # URL (make it a link)
            story.append(Paragraph(f'<font color="blue"><u><link href="{url}">{url}</link></u></font>', citation_style))
            
            # Metadata
            story.append(Paragraph(
                f"<i>Published: {date} | Credibility Score: {credibility:.1f}/10</i>",
                citation_style
            ))
            
            # Snippet
            story.append(Paragraph(f"<i>{snippet}</i>", citation_style))
            story.append(Spacer(1, 0.15*inch))
    
    else:
        story.append(Paragraph(
            "⚠️ No web sources were used in this analysis. "
            "The report was generated without external evidence verification.",
            body_style
        ))
    
    # ============================================================================
    # FOOTER
    # ============================================================================
    
    story.append(Spacer(1, 0.5*inch))
    story.append(Paragraph(
        "<i>End of Report - AI-Augmented Hypothesis Explorer</i>",
        ParagraphStyle('Footer', parent=styles['Normal'], alignment=TA_CENTER, fontSize=9, textColor=colors.grey)
    ))
    
    # Build PDF
    doc.build(story)
    buffer.seek(0)
    
    return buffer


# Backward compatibility function
def generate_pdf(topic: str, summary: str, full_text: str) -> io.BytesIO:
    """
    Original PDF generator without sources - kept for backward compatibility.
    """
    buffer = io.BytesIO()
    
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph(f"<b>AI-Augmented Hypothesis Report</b>", styles["Title"]))
    story.append(Paragraph(f"<b>Topic:</b> {topic}", styles["Heading2"]))
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("<b>Executive Summary</b>", styles["Heading2"]))
    story.append(Paragraph(summary, styles["BodyText"]))
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("<b>Full Investigative Report</b>", styles["Heading2"]))
    story.append(Paragraph(full_text.replace("\n", "<br/>"), styles["BodyText"]))

    doc.build(story)
    buffer.seek(0)
    return buffer